# bitbucket-pipelines.yml

image: node:20.10.0  # Use the Node.js 20 image

pipelines:
  default:
    - step:
        name: Install and Test
        caches:
          - node
        script:
          - npm install          # Install dependencies
          - npm run lint          # Run linter to check code quality
          - npm run build              # Run tests with Jest

  branches:
    main:
      - step:
          name: Install, Test, and Deploy
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run build
           
