# bitbucket-pipelines.yml

image: node:20.10.0

pipelines:
  pull-requests:
    "**": #this runs as default for any branch not elsewhere defined
      - step:
          name: Test and Code coverage
          caches:
            - node
          script:
            - npm install -D
            - npm run lint
            - npm run build
    develop: #this runs as default for any branch not elsewhere defined
      - step:
          name: Test and Code coverage
          caches:
            - node
          script:
            - npm install -D
            - npm run lint
            - npm run build
    master: #this runs as default for any branch not elsewhere defined
      - step:
          name: Test and Code coverage
          caches:
            - node
          script:
            - npm install -D
            - npm run lint
            - npm run build
